name = "psots-telegram-bot-v2"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Environment variables and secrets
vars = {
  ADMIN_ID = "989358143",
  BOT_TOKEN = "${BOT_TOKEN}",
  GOOGLE_CLIENT_ID = "${GOOGLE_CLIENT_ID}",
  GOOGLE_CLIENT_SECRET = "${GOOGLE_CLIENT_SECRET}"
}

# KV namespace bindings
[[kv_namespaces]]
binding = "VIOLATIONS"
id = "3c89be83b87e4cf0b8f91b18bf2dc0e4"

[[kv_namespaces]]
binding = "AUDIT_LOG"
id = "6a727dbadb5c4bb3b1062c319758a0a1"
